In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
voc_size = 10000

In [4]:
one_hot_repr = [one_hot(words, voc_size) for words in sent]
one_hot_repr

[[2596, 1551, 547, 2042],
 [2596, 1551, 547, 3454],
 [2596, 7336, 547, 2903],
 [8225, 4594, 1880, 449, 9970],
 [8225, 4594, 1880, 449, 8959],
 [3619, 2596, 2349, 547, 1128],
 [1396, 7712, 8834, 449]]

In [5]:
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential

In [6]:
import numpy as np

In [7]:
sent_length = 8

embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2596 1551  547 2042]
 [   0    0    0    0 2596 1551  547 3454]
 [   0    0    0    0 2596 7336  547 2903]
 [   0    0    0 8225 4594 1880  449 9970]
 [   0    0    0 8225 4594 1880  449 8959]
 [   0    0    0 3619 2596 2349  547 1128]
 [   0    0    0    0 1396 7712 8834  449]]


In [8]:
dimension = 10
model = Sequential()
model.add(Embedding(voc_size, dimension, input_length=sent_length))
model.compile('adam', 'mse')
print(model.summary())

/Users/hitheshalle/Downloads/ANNdeeplearningNLP/venv310/lib/python3.10/site-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(
2025-06-03 05:10:18.457932: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M2 Pro
2025-06-03 05:10:18.457973: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 16.00 GB
2025-06-03 05:10:18.457982: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 5.33 GB
2025-06-03 05:10:18.458023: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2025-06-03 05:10:18.458047: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [21]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step


array([[[-0.00736356, -0.04252717,  0.03848677,  0.01390835,
          0.01191537,  0.0331519 , -0.02976284, -0.0116167 ,
         -0.00995853, -0.03734912],
        [-0.00736356, -0.04252717,  0.03848677,  0.01390835,
          0.01191537,  0.0331519 , -0.02976284, -0.0116167 ,
         -0.00995853, -0.03734912],
        [-0.00736356, -0.04252717,  0.03848677,  0.01390835,
          0.01191537,  0.0331519 , -0.02976284, -0.0116167 ,
         -0.00995853, -0.03734912],
        [-0.00736356, -0.04252717,  0.03848677,  0.01390835,
          0.01191537,  0.0331519 , -0.02976284, -0.0116167 ,
         -0.00995853, -0.03734912],
        [ 0.04211095,  0.00268465,  0.02154453, -0.03367384,
         -0.0292783 ,  0.04086391,  0.01245185, -0.0011998 ,
          0.02736652, -0.02748942],
        [-0.02647653, -0.01619281,  0.02264911,  0.00307745,
          0.04880554,  0.04275269, -0.01421726,  0.03063231,
         -0.02054006, -0.01826603],
        [-0.04023106,  0.00052452, -0.01413195, -0.0

In [19]:
embedded_docs[0]

array([   0,    0,    0,    0, 2596, 1551,  547, 2042], dtype=int32)

In [18]:
model.predict(np.array([embedded_docs[0]]))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step


array([[[-0.00736356, -0.04252717,  0.03848677,  0.01390835,
          0.01191537,  0.0331519 , -0.02976284, -0.0116167 ,
         -0.00995853, -0.03734912],
        [-0.00736356, -0.04252717,  0.03848677,  0.01390835,
          0.01191537,  0.0331519 , -0.02976284, -0.0116167 ,
         -0.00995853, -0.03734912],
        [-0.00736356, -0.04252717,  0.03848677,  0.01390835,
          0.01191537,  0.0331519 , -0.02976284, -0.0116167 ,
         -0.00995853, -0.03734912],
        [-0.00736356, -0.04252717,  0.03848677,  0.01390835,
          0.01191537,  0.0331519 , -0.02976284, -0.0116167 ,
         -0.00995853, -0.03734912],
        [ 0.04211095,  0.00268465,  0.02154453, -0.03367384,
         -0.0292783 ,  0.04086391,  0.01245185, -0.0011998 ,
          0.02736652, -0.02748942],
        [-0.02647653, -0.01619281,  0.02264911,  0.00307745,
          0.04880554,  0.04275269, -0.01421726,  0.03063231,
         -0.02054006, -0.01826603],
        [-0.04023106,  0.00052452, -0.01413195, -0.0